<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="FailureTraceMetaModel" nsURI="com.criticalsoftware.panorama.failurelogic.FailureTraceMetaModel"
    nsPrefix="FailureTraceMetaModel">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="com.criticalsoftware.panorama.failurelogic"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="FailureTraceModel" eSuperTypes="../../org.eclipse.capra.generic.tracemodel/model/generictrace.xcore#/EPackage/GenericTraceModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propagateTraces" upperBound="-1"
        eType="#//PropagateTo" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="safetyTraces" upperBound="-1"
        eType="#//SafetyTraceability" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropagateTo" eSuperTypes="../../org.eclipse.capra.generic.tracemodel/model/generictrace.xcore#/EPackage/RelatedTo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="failure" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SafetyTraceability" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Failure2Process" eSuperTypes="#//SafetyTraceability">
    <eStructuralFeatures xsi:type="ecore:EReference" name="failure" lowerBound="1"
        eType="ecore:EClass ../../com.criticalsoftware.panorama.failureLogic/failureLogic.ecore#//Failure"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="process" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.app4mc.amalthea.model/model/amalthea.xcore#/EPackage/AbstractProcess"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Failure2Runnable" eSuperTypes="#//SafetyTraceability">
    <eStructuralFeatures xsi:type="ecore:EReference" name="failure" lowerBound="1"
        eType="ecore:EClass ../../com.criticalsoftware.panorama.failureLogic/failureLogic.ecore#//Failure"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runnable" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.app4mc.amalthea.model/model/amalthea.xcore#/EPackage/Runnable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Failure2Event" eSuperTypes="#//SafetyTraceability">
    <eStructuralFeatures xsi:type="ecore:EReference" name="failure" lowerBound="1"
        eType="ecore:EClass ../../com.criticalsoftware.panorama.failureLogic/failureLogic.ecore#//Failure"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1" eType="ecore:EClass ../../org.eclipse.app4mc.amalthea.model/model/amalthea.xcore#/EPackage/OsEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Failure2Semaphore" eSuperTypes="#//SafetyTraceability">
    <eStructuralFeatures xsi:type="ecore:EReference" name="failure" lowerBound="1"
        eType="ecore:EClass ../../com.criticalsoftware.panorama.failureLogic/failureLogic.ecore#//Failure"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semaphore" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.app4mc.amalthea.model/model/amalthea.xcore#/EPackage/Semaphore"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Failure2Label" eSuperTypes="#//SafetyTraceability">
    <eStructuralFeatures xsi:type="ecore:EReference" name="failure" lowerBound="1"
        eType="ecore:EClass ../../com.criticalsoftware.panorama.failureLogic/failureLogic.ecore#//Failure"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" lowerBound="1" eType="ecore:EClass ../../org.eclipse.app4mc.amalthea.model/model/amalthea.xcore#/EPackage/Label"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Failure2Constraint" eSuperTypes="#//SafetyTraceability">
    <eStructuralFeatures xsi:type="ecore:EReference" name="failure" lowerBound="1"
        eType="ecore:EClass ../../com.criticalsoftware.panorama.failureLogic/failureLogic.ecore#//Failure"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.app4mc.amalthea.model/model/amalthea.xcore#/EPackage/AffinityConstraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FailureModel2Task" eSuperTypes="#//SafetyTraceability">
    <eStructuralFeatures xsi:type="ecore:EReference" name="failureModel" lowerBound="1"
        eType="ecore:EClass ../../com.criticalsoftware.panorama.failureLogic/failureLogic.ecore#//FailureModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runnable" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.app4mc.amalthea.model/model/amalthea.xcore#/EPackage/ComponentInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FailureModel2ConstraintsModel" eSuperTypes="#//SafetyTraceability">
    <eStructuralFeatures xsi:type="ecore:EReference" name="failureModel" lowerBound="1"
        eType="ecore:EClass ../../com.criticalsoftware.panorama.failureLogic/failureLogic.ecore#//FailureModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraintsModel" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.app4mc.amalthea.model/model/amalthea.xcore#/EPackage/ConstraintsModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Failure2Component" eSuperTypes="#//SafetyTraceability">
    <eStructuralFeatures xsi:type="ecore:EReference" name="failure" lowerBound="1"
        eType="ecore:EClass ../../com.criticalsoftware.panorama.failureLogic/failureLogic.ecore#//Failure"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.app4mc.amalthea.model/model/amalthea.xcore#/EPackage/ComponentInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FailureModel2Component" eSuperTypes="#//SafetyTraceability">
    <eStructuralFeatures xsi:type="ecore:EReference" name="failureModel" lowerBound="1"
        eType="ecore:EClass ../../com.criticalsoftware.panorama.failureLogic/failureLogic.ecore#//FailureModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.app4mc.amalthea.model/model/amalthea.xcore#/EPackage/ComponentInstance"/>
  </eClassifiers>
</ecore:EPackage>
